### ISSUE TITLE
The 32-bit go program reads the 64-bit program CommandLine will fail.

### ISSUE THREAD

**Issue by GameXG** [winlabs/gowin32#65]
[ERR]commandLine:gowin32: ReadProcessMemory failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

The problem is that uintptr is 32-bit in a 32-bit go program, but 64-bit in a 64-bit target program.

PEB is read from a 64-bit program via ReadProcessMemory, uintptr is 64-bit, but the go program is 32-bit, causing a result error.

All use of ReadProcessMemory should have this problem.

``` go

type PEB struct {
	Reserved1              [2]byte
	BeingDebugged          byte
	Reserved2              [1]byte
	Reserved3              [2]uintptr
	Ldr                    uintptr
	ProcessParameters      uintptr
	Reserved4              [104]byte
	Reserved5              [52]uintptr
	PostProcessInitRoutine uintptr
	Reserved6              [128]byte
	Reserved7              [1]uintptr
	SessionId              uint32
}

```

**Comment by GameXG** [comment]
Well, the actual NtQueryInformationProcess function needs to be processed, it needs to be a 64-bit version.

X86 calls 64-bit functions can refer to:
Https://github.com/rwfpl/rewolf-wow64ext
Https://stackoverflow.com/questions/5714297/is-it-possible-to-read-process-memory-of-a-64-bit-process-from-a-32bit-app

**Comment by dgolub** [comment]
Thank you for making us aware of this issue.  The solution to which you link involves the use of undocumented API functions, which we've generally been avoiding in this library in order to guarantee forward compatibility.  While I recognize that this is a limitation, we don't want to take the risk of building functionality on undocumented interfaces.  Therefore, I'm closing this bug report as WON'T FIX.  The best solution to your issue is probably to build your application as a 64-bit executable.
